from .gemini_client import generate_text
from ..config import get_settings

def _mock_update(original_plan, feedback):
    return "UPDATED PLAN – DEMO MODE\n\nApplied feedback: " + feedback + "\n\n" + original_plan + "\n\nWith Gemini enabled, this section is regenerated by the AI model."

def update_workout_plan(original_plan, feedback, goal, intensity):
    settings = get_settings()
    if settings.mock_ai:
        return _mock_update(original_plan, feedback)
    prompt = f"""
You are FitBuddy's workout-plan revision component.
Original plan:
---BEGIN ORIGINAL PLAN---
{original_plan}
---END ORIGINAL PLAN---
User feedback:
---BEGIN FEEDBACK---
{feedback}
---END FEEDBACK---
Goal: {goal}
Intensity: {intensity}
Create a revised 7-day plan that incorporates reasonable user feedback while preserving the goal and a sensible activity/recovery balance.
Do not blindly follow unsafe requests. Do not diagnose medical conditions or provide treatment.
Include a short safety note. Plain text only.
"""
    return generate_text(prompt, settings.gemini_workout_model)
